2024-08-04 14:37:34,420 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5555
2024-08-04 14:37:34,420 INFO: [33mPress CTRL+C to quit[0m
2024-08-04 14:37:34,421 INFO:  * Restarting with stat
2024-08-04 14:37:34,817 WARNING:  * Debugger is active!
2024-08-04 14:37:34,819 INFO:  * Debugger PIN: 128-870-809
2024-08-04 14:38:40,112 INFO:  * Detected change in '/home/chrizob/Development/code/phase-4/ArtVista/server/app.py', reloading
2024-08-04 14:38:40,261 INFO:  * Restarting with stat
2024-08-04 14:38:41,882 INFO:  * Restarting with stat
2024-08-04 14:41:57,286 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5555
2024-08-04 14:41:57,286 INFO: [33mPress CTRL+C to quit[0m
2024-08-04 14:41:57,286 INFO:  * Restarting with stat
2024-08-04 14:41:57,729 WARNING:  * Debugger is active!
2024-08-04 14:41:57,731 INFO:  * Debugger PIN: 128-870-809
2024-08-04 14:42:14,526 INFO: Request: home route accessed
2024-08-04 14:42:14,531 INFO: 127.0.0.1 - - [04/Aug/2024 14:42:14] "GET / HTTP/1.1" 200 -
2024-08-04 14:42:15,782 ERROR: Error: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/chrizob/Development/code/phase-4/ArtVista/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chrizob/Development/code/phase-4/ArtVista/.venv/lib/python3.12/site-packages/flask/app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/chrizob/Development/code/phase-4/ArtVista/.venv/lib/python3.12/site-packages/flask/app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chrizob/Development/code/phase-4/ArtVista/.venv/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chrizob/Development/code/phase-4/ArtVista/.venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-08-04 14:42:15,789 INFO: 127.0.0.1 - - [04/Aug/2024 14:42:15] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
2024-08-04 14:42:31,578 INFO: User 11 logged in successfully.
2024-08-04 14:42:31,579 INFO: 127.0.0.1 - - [04/Aug/2024 14:42:31] "POST /login HTTP/1.1" 200 -
2024-08-04 14:43:00,263 INFO: Fetched all projects.
2024-08-04 14:43:00,264 INFO: 127.0.0.1 - - [04/Aug/2024 14:43:00] "GET /projects HTTP/1.1" 200 -
2024-08-04 14:43:53,686 INFO: Request: home route accessed
2024-08-04 14:43:53,686 INFO: 127.0.0.1 - - [04/Aug/2024 14:43:53] "GET / HTTP/1.1" 200 -
